action_feat_group_size: 32
batch_size: 4
char_detection:
  face_config: mtcnn.json
  face_det_model: mtcnn.pth
  person_config: cascade_rcnn_x101_64x4d_fpn.json
  person_det_model: cascade_rcnn_x101_64x4d_fpn.pth
  save_path: null
character_name_selection_threshold: 0.5
clip_srts_path: /data/share_user/EmoTx/data/MovieGraph/srt/clip_srt/
data_path: /data/share_user/EmoTx/data
dumps_path: ./dumps
emotic_mapping_path: /data/share_user/EmoTx/data/emotic_mapping.json
epochs: 20
face_feat_dir: _face_features
face_feat_type: generic
feat_info:
  emo:
    face_feat_dim: 4096
    weights: vgg_m_face_bn_fer_dag.pth
  generic:
    face_feat_dim: 512
    scene_feat_dim: 2048
  mvit_v1:
    scene_feat_dim: 768
    weights: MVIT_B_32x3_f294077834.pyth
  resnet50_fer:
    face_feat_dim: 2048
    weights: resnet50_fer.pth
  resnet50_places:
    scene_feat_dim: 2048
    weights: resnet50_places365.pth.tar
  roberta:
    srt_feat_dim: 768
feat_sampling_rate: 8
get_char_targets: true
get_scene_targets: true
gpu_id: 0
hugging_face_cache_path: ../cache/
joint_character_modeling: true
lr: 1.0e-05
max_feats: 300
max_possible_vid_frame_no: 17500
max_srt_feats: 300
mg_videos_dir: mg_videos
model_name: M5_0.L2.N4.e5.t10.mS.gC.inFrSr.8_
model_name_suffix: ''
model_no: 5.0
num_chars: 4
num_cpus: 9
num_enc_layers: 2
pkl_name: 2017-11-02-51-7637_py3.pkl
pkl_path: /data/share_user/EmoTx/data/MovieGraph/mg/py3loader/
pos_weight:
  '10':
  - 2.67218201
  - 2.91079295
  - 2.36587678
  - 4.29210134
  - 3.74098798
  - 4.70900322
  - 4.57456829
  - 4.96806723
  - 4.72741935
  - 5.60037175
  '25':
  - 3.76215098
  - 4.0715859
  - 3.36492891
  - 5.86289121
  - 5.1481976
  - 6.40353698
  - 6.22919937
  - 6.7394958
  - 6.42741935
  - 7.55947955
  - 8.63389121
  - 8.3597561
  - 8.26559356
  - 9.41855204
  - 8.39795918
  - 10.74744898
  - 11.75623269
  - 10.09638554
  - 10.93005181
  - 12.15714286
  - 12.62426036
  - 14.98958333
  - 12.70535714
  - 16.18283582
  - 17.56854839
  '26':
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
random_feat_selection: true
resource_path: /data/share_user/EmoTx/data/MovieGraph/resources/
save_path: ./checkpoints/
saved_model_path: /data/share_user/EmoTx/data/pretrained_models/
scene_feat_dir: _scene_features
scene_feat_type: mvit_v1
seed: 0
shuffle_characters: false
srt_feat_dir: srt_feats
srt_feat_model: roberta
srt_feat_pretrained: false
srt_feat_type: independent
target_prediction_threshold: 0.5
top_k: 10
track_name_metadata_dir: track_names/metadata
track_names_dir: track_names
tracks_dir: character_tracks
use_char_feats: true
use_emotic_mapping: false
use_scene_feats: true
use_srt_cls_only: true
use_srt_feats: true
vid_fps: 23.976023976023978
wandb:
  entity: lelour1217
  logging: true
  project: emotx_cs577
  sweep_id: ''
  sweep_run_count: 100
  sweeps: false
