wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: huggingface
    huggingface_version: 4.18.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.5
    start_time: 1697731086
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      3:
      - 16
      4: 3.6.5
      5: 0.12.21
      6: 4.18.0
      8:
      - 5
action_feat_group_size:
  desc: null
  value: 32
batch_size:
  desc: null
  value: 4
char_detection:
  desc: null
  value:
    face_config: mtcnn.json
    face_det_model: mtcnn.pth
    person_config: cascade_rcnn_x101_64x4d_fpn.json
    person_det_model: cascade_rcnn_x101_64x4d_fpn.pth
    save_path: null
character_name_selection_threshold:
  desc: null
  value: 0.5
clip_srts_path:
  desc: null
  value: /data/share_user/EmoTx/data/MovieGraph/srt/clip_srt/
data_path:
  desc: null
  value: /data/share_user/EmoTx/data
dumps_path:
  desc: null
  value: ./dumps
emotic_mapping_path:
  desc: null
  value: /data/share_user/EmoTx/data/emotic_mapping.json
epochs:
  desc: null
  value: 20
face_feat_dir:
  desc: null
  value: _face_features
face_feat_type:
  desc: null
  value: resnet50_fer
feat_info:
  desc: null
  value:
    emo:
      face_feat_dim: 4096
      weights: vgg_m_face_bn_fer_dag.pth
    generic:
      face_feat_dim: 512
      scene_feat_dim: 2048
    mvit_v1:
      scene_feat_dim: 768
      weights: MVIT_B_32x3_f294077834.pyth
    resnet50_fer:
      face_feat_dim: 2048
      weights: resnet50_fer.pth
    resnet50_places:
      scene_feat_dim: 2048
      weights: resnet50_places365.pth.tar
    roberta:
      srt_feat_dim: 768
feat_sampling_rate:
  desc: null
  value: 8
get_char_targets:
  desc: null
  value: true
get_scene_targets:
  desc: null
  value: true
gpu_id:
  desc: null
  value: 0
hugging_face_cache_path:
  desc: null
  value: ../cache/
joint_character_modeling:
  desc: null
  value: true
lr:
  desc: null
  value: 1.0e-05
max_feats:
  desc: null
  value: 300
max_possible_vid_frame_no:
  desc: null
  value: 17500
max_srt_feats:
  desc: null
  value: 300
mg_videos_dir:
  desc: null
  value: mg_videos
model_name:
  desc: null
  value: M4_0.L2.N4.e5.t10.mS.rC.inFrSr.8_
model_name_suffix:
  desc: null
  value: ''
model_no:
  desc: null
  value: 4.0
num_chars:
  desc: null
  value: 4
num_cpus:
  desc: null
  value: 9
num_enc_layers:
  desc: null
  value: 2
pkl_name:
  desc: null
  value: 2017-11-02-51-7637_py3.pkl
pkl_path:
  desc: null
  value: /data/share_user/EmoTx/data/MovieGraph/mg/py3loader/
pos_weight:
  desc: null
  value:
    '10':
    - 2.67218201
    - 2.91079295
    - 2.36587678
    - 4.29210134
    - 3.74098798
    - 4.70900322
    - 4.57456829
    - 4.96806723
    - 4.72741935
    - 5.60037175
    '25':
    - 3.76215098
    - 4.0715859
    - 3.36492891
    - 5.86289121
    - 5.1481976
    - 6.40353698
    - 6.22919937
    - 6.7394958
    - 6.42741935
    - 7.55947955
    - 8.63389121
    - 8.3597561
    - 8.26559356
    - 9.41855204
    - 8.39795918
    - 10.74744898
    - 11.75623269
    - 10.09638554
    - 10.93005181
    - 12.15714286
    - 12.62426036
    - 14.98958333
    - 12.70535714
    - 16.18283582
    - 17.56854839
    '26':
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
random_feat_selection:
  desc: null
  value: true
resource_path:
  desc: null
  value: /data/share_user/EmoTx/data/MovieGraph/resources/
save_path:
  desc: null
  value: ./checkpoints/
saved_model_path:
  desc: null
  value: /data/share_user/EmoTx/data/pretrained_models/
scene_feat_dir:
  desc: null
  value: _scene_features
scene_feat_type:
  desc: null
  value: mvit_v1
seed:
  desc: null
  value: 0
shuffle_characters:
  desc: null
  value: false
srt_feat_dir:
  desc: null
  value: srt_feats
srt_feat_model:
  desc: null
  value: roberta
srt_feat_pretrained:
  desc: null
  value: false
srt_feat_type:
  desc: null
  value: independent
target_prediction_threshold:
  desc: null
  value: 0.5
top_k:
  desc: null
  value: 10
track_name_metadata_dir:
  desc: null
  value: track_names/metadata
track_names_dir:
  desc: null
  value: track_names
tracks_dir:
  desc: null
  value: character_tracks
use_char_feats:
  desc: null
  value: true
use_emotic_mapping:
  desc: null
  value: false
use_scene_feats:
  desc: null
  value: true
use_srt_cls_only:
  desc: null
  value: true
use_srt_feats:
  desc: null
  value: true
vid_fps:
  desc: null
  value: 23.976023976023978
wandb:
  desc: null
  value:
    entity: lelour1217
    logging: true
    project: emotx_cs577
    sweep_id: ''
    sweep_run_count: 100
    sweeps: false
